// Partner information dated 18 September 2026. Institute name is not yet decided.
export const dunjaMartinCopy = {
  de: {
    title: "Dr. med. Dunja Martin | Online-Begleitung | Cell Clinics",
    description: "Neurologin Dr. med. Dunja Martin: Online-Beratung zu Zellgesundheit, Longevity und Leistungsfähigkeit sowie Vorträge und Gesundheitstage für Unternehmen und Vereine.",
    label: "Netzwerkpartnerin · Online & vor Ort", headline: "Gesundheit verstehen. Alltag neu gestalten.",
    intro: "Dr. med. Dunja Martin verbindet ihren neurologischen Hintergrund mit funktioneller Medizin, Zellgesundheit und Longevity. Ihre Begleitung findet online statt — für Unternehmen und Vereine auch persönlich vor Ort.",
    back: "Alle Netzwerkpartner", book: "Erstgespräch vereinbaren", website: "Website besuchen",
    facts: ["Fachrichtung Neurologie", "Online-Begleitung", "Vorträge & Gesundheitstage", "Deutsch & Englisch"],
    aboutLabel: "Dr. med. Dunja Martin", aboutTitle: "Ein Blick auf den ganzen Menschen.",
    about: "Migräne, Erschöpfung, Brain Fog und Neurodegeneration zählen zu ihren fachlichen Schwerpunkten. In ihrer heutigen Arbeit verbindet Dr. Martin funktionelle Medizin mit Fragen der Zellgesundheit und langfristigen Leistungsfähigkeit. Erweiterte Laboranalysen werden in die Beratung einbezogen; die Abstimmung mit den behandelnden Ärzten vor Ort ist Teil ihres Ansatzes.",
    offerLabel: "Zwei Wege der Zusammenarbeit", offerTitle: "Bei Ihnen zu Hause. In Ihrem Unternehmen.",
    offers: [["Individuelle Online-Begleitung", "Beratung, Aufklärung und Coaching rund um Zellgesundheit, Longevity und Performance. Die Termine werden individuell vereinbart und finden ortsunabhängig statt."], ["Impulse für Teams & Vereine", "Impulsvorträge, Keynotes, Schulungen und Gesundheitstage für Unternehmen, Vereine und Gesundheitszentren — mit Themen wie Fokus, Vitalität und Leistungsfähigkeit."]],
    focusLabel: "Themen", focusTitle: "Wissen, das im Alltag ankommt.",
    topics: [["Zellgesundheit & Longevity", "Zusammenhänge verstehen und persönliche Gesundheitsziele einordnen."], ["Fokus & Leistungsfähigkeit", "Beratung für Unternehmer, Berufstätige und Sportler."], ["Neurologische Perspektive", "Aufklärung zu Migräne, Erschöpfung, Brain Fog und Demenzprävention."]],
    note: "Das Angebot umfasst Beratung, Schulung und Coaching. Es ersetzt keine notwendige Untersuchung oder Behandlung vor Ort. Welche Begleitung zu Ihrer Situation passt, wird im Erstgespräch geklärt.",
    contactTitle: "Lernen Sie Dr. Martin kennen.", contactBody: "Wählen Sie einen Termin für ein Erstgespräch oder nehmen Sie direkt Kontakt auf. Termine nach Vereinbarung.",
    location: "Kontaktadresse · keine offene Sprechstunde", locationNote: "Die individuelle Begleitung erfolgt online; Unternehmens- und Vereinsangebote vor Ort nach Absprache.",
    portraitAlt: "Dr. med. Dunja Martin in weißer Bluse und heller Hose", secondAlt: "Porträt von Dr. med. Dunja Martin im Freien",
    source: "Angaben aus der Partnerinformation vom 18. September 2026. Fotos: Website von Dr. Dunja Martin."
  },
  en: {
    title: "Dr. med. Dunja Martin | Online guidance | Cell Clinics",
    description: "Neurologist Dr. med. Dunja Martin offers online guidance on cell health, longevity and performance, plus talks and health days for businesses and clubs.",
    label: "Network partner · Online & on site", headline: "Understand health. Rethink everyday life.",
    intro: "Dr. med. Dunja Martin combines her neurological background with functional medicine, cell health and longevity. She offers online guidance, with in-person formats for businesses and clubs.",
    back: "All network partners", book: "Book an introductory call", website: "Visit website",
    facts: ["Neurology", "Online guidance", "Talks & health days", "German & English"],
    aboutLabel: "Dr. med. Dunja Martin", aboutTitle: "A perspective on the whole person.",
    about: "Migraine, exhaustion, brain fog and neurodegeneration are among her areas of focus. Dr. Martin connects functional medicine with cell health and long-term performance. Extended laboratory analyses inform her guidance, in coordination with the physicians providing local care.",
    offerLabel: "Two ways to work together", offerTitle: "At home. At your workplace.",
    offers: [["Individual online guidance", "Consultation, education and coaching on cell health, longevity and performance. Appointments are arranged individually and take place online."], ["Sessions for teams & clubs", "Talks, keynotes, training and health days for businesses, clubs and health centres, covering focus, vitality and performance."]],
    focusLabel: "Topics", focusTitle: "Knowledge for everyday life.",
    topics: [["Cell health & longevity", "Understanding connections and putting personal health goals into context."], ["Focus & performance", "Guidance for entrepreneurs, professionals and athletes."], ["A neurological perspective", "Education on migraine, exhaustion, brain fog and dementia prevention."]],
    note: "Services include consultation, education and coaching. They do not replace necessary in-person medical examination or treatment. The introductory call helps establish which support is appropriate.",
    contactTitle: "Meet Dr. Martin.", contactBody: "Book an introductory call or get in touch directly. Appointments by arrangement.",
    location: "Contact address · no walk-in consultations", locationNote: "Individual guidance is online; on-site services for businesses and clubs are arranged separately.",
    portraitAlt: "Dr. med. Dunja Martin wearing a white blouse and light trousers", secondAlt: "Outdoor portrait of Dr. med. Dunja Martin",
    source: "Information supplied on 18 September 2026. Photos: Dr. Dunja Martin's website."
  },
  es: {
    title: "Dra. Dunja Martin | Asesoramiento online | Cell Clinics",
    description: "La neuróloga Dra. Dunja Martin ofrece asesoramiento online sobre salud celular, longevidad y rendimiento, y charlas para empresas y asociaciones.",
    label: "Profesional de la red · Online y presencial", headline: "Comprender la salud. Transformar el día a día.",
    intro: "La Dra. Dunja Martin combina su formación en neurología con medicina funcional, salud celular y longevidad. Ofrece acompañamiento online y formatos presenciales para empresas y asociaciones.",
    back: "Todos los profesionales", book: "Reservar una primera conversación", website: "Visitar la web",
    facts: ["Neurología", "Acompañamiento online", "Charlas y jornadas de salud", "Alemán e inglés"],
    aboutLabel: "Dra. Dunja Martin", aboutTitle: "Una mirada a la persona en su conjunto.",
    about: "La migraña, el agotamiento, la niebla mental y la neurodegeneración forman parte de sus áreas de interés. Su trabajo conecta medicina funcional, salud celular y rendimiento a largo plazo. Incorpora análisis de laboratorio ampliados al asesoramiento, en coordinación con los médicos que atienden presencialmente a cada persona.",
    offerLabel: "Dos formas de colaborar", offerTitle: "En casa. En su empresa.",
    offers: [["Acompañamiento individual online", "Asesoramiento, formación y coaching sobre salud celular, longevidad y rendimiento. Citas online concertadas individualmente."], ["Sesiones para equipos y asociaciones", "Charlas, conferencias, formación y jornadas de salud para empresas, asociaciones y centros de salud sobre concentración, vitalidad y rendimiento."]],
    focusLabel: "Temas", focusTitle: "Conocimiento para la vida cotidiana.",
    topics: [["Salud celular y longevidad", "Comprender las conexiones y contextualizar los objetivos personales de salud."], ["Concentración y rendimiento", "Asesoramiento para empresarios, profesionales y deportistas."], ["Perspectiva neurológica", "Información sobre migraña, agotamiento, niebla mental y prevención de la demencia."]],
    note: "La oferta incluye asesoramiento, formación y coaching. No sustituye las exploraciones o tratamientos médicos presenciales necesarios. La primera conversación permite valorar el acompañamiento adecuado.",
    contactTitle: "Conozca a la Dra. Martin.", contactBody: "Reserve una primera conversación o contacte directamente. Citas concertadas.",
    location: "Dirección de contacto · sin consulta abierta", locationNote: "El acompañamiento individual es online; las actividades presenciales para empresas y asociaciones se acuerdan por separado.",
    portraitAlt: "Dra. Dunja Martin con blusa blanca y pantalón claro", secondAlt: "Retrato de la Dra. Dunja Martin al aire libre",
    source: "Información facilitada el 18 de septiembre de 2026. Fotos: web de la Dra. Dunja Martin."
  }
};
