export const marcStrackeCopy = {
  de: {
    title: "Dr. Marc Stracke · Privatpraxis in Lübeck", intro: "Privatpraxis für ganzheitliche Medizin in Lübeck. Ein persönlicher Blick auf Ihre Vorgeschichte, Ihre Beschwerden und Ihre gesundheitlichen Ziele.",
    back: "Zum Netzwerk", book: "Termin vereinbaren", website: "Website besuchen", aboutLabel: "Ihr Arzt", aboutTitle: "Erfahrung und Zeit für Ihre Gesundheit.",
    about: "Dr. med. Marc Stracke ist Facharzt für Allgemeinmedizin mit Qualifikationen in Ernährungsmedizin und Manueller Medizin. Nach seiner Tätigkeit in Bad Schwartau führt er seine Praxis seit 2020 in Lübeck. Seine Arbeit verbindet ärztliche Betreuung mit individuellem Gesundheitscoaching.",
    focusLabel: "Praxisschwerpunkte", focusTitle: "Den Menschen als Ganzes betrachten.",
    topics: [["Mitochondriale Medizin", "Zum Angebot gehören mitochondriale Medizin, IHHT und die me2.vie-Systemtherapie. Die Auswahl erfolgt nach individueller ärztlicher Beurteilung."], ["Ernährung & Mikronährstoffe", "Ernährungsgewohnheiten und Nährstoffstatus werden im Zusammenhang mit Ihren Beschwerden und Gesundheitszielen betrachtet."], ["Manuelle Medizin", "Untersuchung von Beweglichkeit, Muskeln und Gelenken als Teil einer persönlichen Behandlungsplanung."]],
    visitLabel: "Ihr Besuch", visitTitle: "Ein persönlicher Einstieg.", visitBody: "Am Anfang stehen ein ausführliches Gespräch und Ihre Krankengeschichte. Ein Anamnesebogen hilft bei der Vorbereitung. Die Praxis behandelt Privatversicherte und Selbstzahler; die Abrechnung erfolgt nach GOÄ. Kosten und mögliche Erstattung klären Sie bitte vorab mit Praxis und Versicherung.", process: "Informationen für Neupatienten", practiceAlt: "Empfangs- und Wartebereich der Praxis Dr. Stracke in Lübeck",
    contactTitle: "Kontakt zur Praxis", contactBody: "Vereinbaren Sie Ihren Termin direkt über Doctolib oder wenden Sie sich mit Fragen an das Praxisteam.", note: "Diagnostik und Behandlung werden individuell ärztlich festgelegt. Die medizinische Verantwortung liegt bei der behandelnden Praxis."
  },
  en: {
    title: "Dr. Marc Stracke · Private practice in Lübeck", intro: "Private practice for holistic medicine in Lübeck. A personal approach to your medical history, concerns and health goals.",
    back: "Back to network", book: "Book an appointment", website: "Visit website", aboutLabel: "Your physician", aboutTitle: "Experience and time for your health.",
    about: "Dr. med. Marc Stracke is a specialist in general medicine with qualifications in nutritional and manual medicine. Following his work in Bad Schwartau, he has run his practice in Lübeck since 2020. His work combines medical care with individual health coaching.",
    focusLabel: "Areas of focus", focusTitle: "Considering the whole person.", topics: [["Mitochondrial medicine", "The practice offers mitochondrial medicine, IHHT and me2.vie system therapy, selected after individual medical assessment."], ["Nutrition & micronutrients", "Eating habits and nutrient status are considered alongside your concerns and health goals."], ["Manual medicine", "Assessment of mobility, muscles and joints as part of individual treatment planning."]],
    visitLabel: "Your visit", visitTitle: "A personal first step.", visitBody: "Your first visit starts with an in-depth conversation and your medical history. A medical history form helps you prepare. The practice welcomes privately insured and self-paying patients and bills according to the German GOÄ fee schedule. Please clarify costs and possible reimbursement with the practice and your insurer in advance.", process: "Information for new patients", practiceAlt: "Reception and waiting area at Dr. Stracke’s practice in Lübeck",
    contactTitle: "Contact the practice", contactBody: "Book directly through Doctolib or contact the practice team with your questions.", note: "Diagnostics and treatment are determined individually by the physician. Medical responsibility rests with the treating practice."
  },
  es: {
    title: "Dr. Marc Stracke · Consulta privada en Lübeck", intro: "Consulta privada de medicina integral en Lübeck. Una atención personal a su historia clínica, sus necesidades y sus objetivos de salud.",
    back: "Volver a la red", book: "Reservar cita", website: "Visitar web", aboutLabel: "Su médico", aboutTitle: "Experiencia y tiempo para su salud.",
    about: "El Dr. med. Marc Stracke es especialista en medicina general con formación en medicina nutricional y manual. Tras ejercer en Bad Schwartau, dirige su consulta en Lübeck desde 2020. Combina atención médica y asesoramiento individual en salud.",
    focusLabel: "Áreas de atención", focusTitle: "Una visión integral de la persona.", topics: [["Medicina mitocondrial", "La consulta ofrece medicina mitocondrial, IHHT y terapia me2.vie, seleccionadas tras valoración médica individual."], ["Nutrición y micronutrientes", "Los hábitos alimentarios y el estado nutricional se consideran junto con sus molestias y objetivos de salud."], ["Medicina manual", "Exploración de movilidad, músculos y articulaciones como parte de la planificación individual."]],
    visitLabel: "Su visita", visitTitle: "Un primer paso personal.", visitBody: "La primera visita comienza con una conversación detallada y su historia clínica. Un cuestionario ayuda a prepararla. La consulta atiende a pacientes con seguro privado y de pago directo; factura según el baremo alemán GOÄ. Consulte previamente los costes y el posible reembolso con la consulta y su aseguradora.", process: "Información para nuevos pacientes", practiceAlt: "Recepción y sala de espera de la consulta del Dr. Stracke en Lübeck",
    contactTitle: "Contactar con la consulta", contactBody: "Reserve directamente a través de Doctolib o contacte con el equipo para sus preguntas.", note: "El diagnóstico y el tratamiento se determinan individualmente por criterio médico. La responsabilidad médica corresponde a la consulta tratante."
  }
};
