// Review draft. Resolve all markers before merging/publishing.
export const privacyCopy = {
  de: {
    title: "Datenschutzerklärung", home: "Start", date: "Stand: Oktober 2026",
    gtmNotice: "Google Tag Manager: Wir binden den Container GTM-TFZJGN3F von Google über www.googletagmanager.com ein. Beim Laden werden IP-Adresse und HTTP-Anfragedaten an Google übertragen. Die Steuerung der enthaltenen Tags erfolgt über die Konfiguration in CookieYes und Google Tag Manager, nicht über eine zusätzliche Sperre im Anwendungscode..",
    sections: [
      ["1. Verantwortlicher", "Cell Clinics ist ein Angebot der Cell Education - The Institute GmbH & Co. KG, Frankfurter Straße 7, 61462 Königstein im Taunus, Deutschland. Verantwortlich für die Verarbeitung: Cell Education - The Institute GmbH & Co. KG. Kontakt: info@cell-education.com."],
      ["2. Hosting und Server-Logfiles", "Wir nutzen Vercel Inc., USA, zur Bereitstellung der Website. Dabei können IP-Adresse, Datum und Uhrzeit, abgerufene Seite sowie Browserinformationen verarbeitet werden. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse ist der sichere und zuverlässige Betrieb.. Für Übermittlungen in die USA kommen das EU-US Data Privacy Framework bei gültiger Zertifizierung oder Standardvertragsklauseln in Betracht.."],
      ["3. Cookies", "NEXT_LOCALE speichert die Sprachwahl als technisch notwendiges Session-Cookie (Path=/, SameSite=Lax). Es endet mit der Browsersitzung; eine Sitzungswiederherstellung des Browsers kann dies verlängern. Grundlage: § 25 Abs. 2 TDDDG sowie Art. 6 Abs. 1 lit. f DSGVO. CookieYes speichert die Consent-Entscheidung in einem notwendigen Cookie.. Grundlage: § 25 Abs. 2 TDDDG und Art. 6 Abs. 1 lit. c DSGVO. Statistik und Marketing sind optional und ohne ausdrückliche Zustimmung deaktiviert. Für optionale Cookies gelten § 25 Abs. 1 TDDDG und Art. 6 Abs. 1 lit. a DSGVO.."],
      ["4. Partneranfragen", "Das Formular verarbeitet Klinikname, Land, Kliniktyp, Beruf, Ansprechpartner, E-Mail sowie optional Website und Telefon; hinzu kommen Einwilligung und Zeitpunkt. Zweck ist die Bearbeitung Ihrer Partnerschaftsanfrage und die Vorbereitung einer möglichen Zusammenarbeit, Art. 6 Abs. 1 lit. b DSGVO. Die eigene API versendet die Angaben per E-Mail, bei konfiguriertem Resend-Schlüssel über Resend, andernfalls über FormSubmit. Standardempfänger ist info@cell-education.com.. Es gibt keine Formulardatenbank im Anwendungscode.."],
      ["5. Regionsanfragen von Patienten", "Wir verarbeiten Name, E-Mail, PLZ/Ort, Ihre Einwilligung und den Zeitpunkt, um Ihre Regionsanfrage zu bearbeiten und Sie entsprechend Ihrer Anfrage zu kontaktieren. Rechtsgrundlage ist Art. 6 Abs. 1 lit. a DSGVO. Die Einwilligung können Sie jederzeit mit Wirkung für die Zukunft über info@cell-education.com widerrufen. Versandweg und Empfänger entsprechen Abschnitt 4. Bitte senden Sie keine Gesundheitsdaten über dieses Formular; es enthält kein Symptom- oder Beschwerdefeld.."],
      ["6. Schutz der Formulare", "Zum Schutz vor automatisierten Anfragen verarbeiten wir die IP-Adresse kurzfristig zur Signierung eines Formular-Tokens und bilden daraus einen HMAC-Schlüssel für ein prozesslokales Rate-Limit. Zähler haben ein einstündiges Zeitfenster und werden beim nächsten Zugriff nach Ablauf oder beim Prozessende entfernt; Tokens sind bis zu 24 Stunden gültig. Hinzu kommen ein unsichtbares Honeypot-Feld und eine Mindest-Ausfüllzeit. Rechtsgrundlage: Art. 6 Abs. 1 lit. f DSGVO, Schutz vor Missbrauch. Formularinhalte werden nicht in den anwendungsseitigen Fehlerprotokollen erfasst; Hostingprotokolle siehe Abschnitt 2."],
      ["7. Standort und Praxissuche", "Die Standortfunktion benötigt Ihre Browserfreigabe. Die Koordinaten werden im Browser für Entfernungen verwendet und von unserem Anwendungscode nicht an einen Geocoding-Server gesendet. Rechtsgrundlage: Art. 6 Abs. 1 lit. a DSGVO. Sie können die Berechtigung im Browser widerrufen. Bei Eingabe von PLZ/Ort übermittelt unsere API den Suchtext, das gewählte Land und die Browsersprache an Nominatim (nominatim.openstreetmap.org); die Besucher-IP wird nicht weitergereicht. Die Suchantwort kann 24 Stunden serverseitig zwischengespeichert werden. Grundlage ist Art. 6 Abs. 1 lit. f DSGVO, Bereitstellung der gewünschten Suche.. Praxisdaten und Koordinaten werden lokal ausgeliefert; die derzeitige Netzwerkansicht lädt keine externen Kartenkacheln."],
      ["8. Videos, Links und lokale Ressourcen", "Das Vimeo-Vorschaubild wird lokal geladen. Erst nach Ihrem Klick auf den entsprechend beschrifteten Button verbindet sich der Browser mit Vimeo; dabei können IP-Adresse, Browserinformationen und Nutzungsdaten übertragen werden. Grundlage ist Ihre Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO und, soweit erforderlich, § 25 Abs. 1 TDDDG. Der Player nutzt dnt=1; dies ersetzt keine Einwilligung.. Durch Verlassen oder Neuladen der Seite beenden Sie den eingebetteten Player. YouTube ist nur extern verlinkt und wird hier nicht eingebettet. Schriftdateien, Bilder und Anwendungsskripte werden lokal bereitgestellt; Google Fonts wird nur beim Build abgerufen, nicht vom Browser der Besucher."],
      ["9. CookieYes und Widerruf", "Bei konfigurierter Site-ID setzen wir CookieYes von CookieYes Limited, Vereinigtes Königreich, zur Verwaltung und zum Nachweis Ihrer Cookie-Entscheidung ein. Verarbeitet werden Entscheidung, Zeitstempel und eine pseudonyme Consent-Kennung; laut Anbieter wird die IP-Adresse maskiert. Eine vollständige Anonymität wird nicht zugesichert. Für das Vereinigte Königreich besteht ein Angemessenheitsbeschluss der EU. Rechtsgrundlage ist Art. 6 Abs. 1 lit. c in Verbindung mit Art. 7 Abs. 1 DSGVO. Über Cookie-Einstellungen im Footer können Sie Ihre Auswahl ändern und Einwilligungen widerrufen.. Ohne Site-ID wird kein CookieYes-Banner geladen. Google Analytics und Meta-Pixel sind nur technisch vorbereitet und ohne IDs nicht aktiv; vor einer Aktivierung müssen die Datenschutzangaben ergänzt werden."],
      ["10. Ihre Rechte", "Im gesetzlichen Rahmen haben Sie Rechte auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung (Art. 18), Mitteilung (Art. 19) und Datenübertragbarkeit (Art. 20). Sie können Verarbeitungen aufgrund berechtigter Interessen aus Gründen Ihrer besonderen Situation nach Art. 21 widersprechen; gegen Direktwerbung jederzeit. Eine Einwilligung können Sie jederzeit für die Zukunft widerrufen; die vorherige Rechtmäßigkeit bleibt unberührt. Kontakt: info@cell-education.com. Sie können sich bei einer Aufsichtsbehörde beschweren, insbesondere beim Hessischen Beauftragten für Datenschutz und Informationsfreiheit, Postfach 3163, 65021 Wiesbaden."]
    ]
  },
  en: {
    title: "Privacy policy", home: "Home", date: "Last updated: October 2026",
    gtmNotice: "Google Tag Manager: We embed Google's container GTM-TFZJGN3F through www.googletagmanager.com. Loading it transmits IP addresses and HTTP request data to Google. Its tags are controlled through CookieYes and Google Tag Manager configuration, not an additional application-level gate..",
    sections: [
      ["1. Controller", "Cell Clinics is a service of Cell Education - The Institute GmbH & Co. KG, Frankfurter Straße 7, 61462 Königstein im Taunus, Germany. The controller is Cell Education - The Institute GmbH & Co. KG. Contact: info@cell-education.com."],
      ["2. Hosting and server logs", "We use Vercel Inc., USA, to host this website. IP addresses, dates, times, requested pages and browser information may be processed. The basis is Article 6(1)(f) GDPR; our legitimate interest is secure and reliable operation.. US transfers may rely on the EU-US Data Privacy Framework where certification is valid, or standard contractual clauses.."],
      ["3. Cookies", "NEXT_LOCALE stores the language preference as a necessary session cookie (Path=/, SameSite=Lax). It expires at the end of the browser session; browser session restoration may extend this. Basis: section 25(2) TDDDG and Article 6(1)(f) GDPR. CookieYes stores consent choices in a necessary cookie.. Basis: section 25(2) TDDDG and Article 6(1)(c) GDPR. Statistics and marketing are optional and disabled without express consent. Optional cookies rely on section 25(1) TDDDG and Article 6(1)(a) GDPR.."],
      ["4. Partner inquiries", "The form processes practice name, country, practice type, profession, contact person, email and optionally website and phone, together with consent and submission time. The purpose is to respond to your partnership inquiry and prepare possible cooperation, Article 6(1)(b) GDPR. Our API sends the details by email through Resend when a key is configured, otherwise through FormSubmit. The default recipient is info@cell-education.com.. Application code has no form database.."],
      ["5. Patient regional inquiries", "We process your name, email, postcode/city, consent and submission time to respond to your regional inquiry and contact you as requested. The basis is Article 6(1)(a) GDPR. You may withdraw consent for the future at info@cell-education.com. Delivery and recipients are as described in section 4. Do not submit health data; there is no symptom or complaint field.."],
      ["6. Form security", "To prevent automated abuse, we briefly process IP addresses to sign form tokens and derive an HMAC key for a process-local rate limit. Counters use a one-hour window and are removed on the next access after expiry or when the process ends; tokens are valid for up to 24 hours. A hidden honeypot and minimum completion time also apply. Basis: Article 6(1)(f) GDPR, abuse prevention. Application error logs do not record form contents; see section 2 for hosting logs."],
      ["7. Location and practice search", "The location feature requires browser permission. Coordinates are used in your browser to calculate distances and are not sent to a geocoding server by our application. Basis: Article 6(1)(a) GDPR. You can revoke permission in your browser. For postcode/city searches, our API sends the search text, selected country and browser language to Nominatim (nominatim.openstreetmap.org), without forwarding your IP address. Search responses may be cached for 24 hours. Basis: Article 6(1)(f) GDPR, providing the requested search.. Practice data and coordinates are served locally; the current network view does not load external map tiles."],
      ["8. Videos, links and local resources", "The Vimeo preview is loaded locally. Only clicking the labelled button connects your browser to Vimeo, which may receive your IP address, browser information and usage data. Basis: Article 6(1)(a) GDPR and, where applicable, section 25(1) TDDDG. The player uses dnt=1; this does not replace consent.. Leaving or reloading the page stops the embedded player. YouTube is an external link only. Fonts, images and application scripts are served locally; Google Fonts is fetched at build time, not by visitors' browsers."],
      ["9. CookieYes and withdrawal", "When a site ID is configured, CookieYes Limited, United Kingdom, manages and records cookie choices. Decisions, timestamps and a pseudonymous consent identifier are processed; the provider states that IP addresses are masked. Full anonymity is not guaranteed. The UK is covered by an EU adequacy decision. Basis: Article 6(1)(c) in conjunction with Article 7(1) GDPR. Use Cookie settings in the footer to change or withdraw consent.. No CookieYes banner loads without a site ID. Google Analytics and Meta Pixel are prepared only and inactive without IDs; this policy must be completed before activation."],
      ["10. Your rights", "Subject to applicable conditions, you have rights of access (Article 15 GDPR), rectification (16), erasure (17), restriction (18), notification (19) and portability (20). Under Article 21 you may object to processing based on legitimate interests for reasons relating to your situation, and to direct marketing at any time. Consent may be withdrawn prospectively without affecting prior lawful processing. Contact info@cell-education.com. You may complain to a supervisory authority, particularly the Hessian Commissioner for Data Protection and Freedom of Information, Postfach 3163, 65021 Wiesbaden, Germany."]
    ]
  },
  es: {
    title: "Política de privacidad", home: "Inicio", date: "Actualización: octubre de 2026",
    gtmNotice: "Google Tag Manager: Integramos el contenedor de Google GTM-TFZJGN3F mediante www.googletagmanager.com. Al cargarlo se transmiten a Google la dirección IP y datos de la solicitud HTTP. Las etiquetas se controlan mediante la configuración de CookieYes y Google Tag Manager, sin un bloqueo adicional en la aplicación..",
    sections: [
      ["1. Responsable", "Cell Clinics es un servicio de Cell Education - The Institute GmbH & Co. KG, Frankfurter Straße 7, 61462 Königstein im Taunus, Alemania. El responsable del tratamiento es Cell Education - The Institute GmbH & Co. KG. Contacto: info@cell-education.com."],
      ["2. Alojamiento y registros", "Vercel Inc., EE. UU., aloja la web. Pueden tratarse direcciones IP, fechas, horas, páginas solicitadas e información del navegador. Base: art. 6.1.f RGPD; interés legítimo en un funcionamiento seguro y fiable.. Las transferencias a EE. UU. pueden basarse en el Marco de Privacidad de Datos UE-EE. UU. si existe certificación vigente o en cláusulas contractuales tipo.."],
      ["3. Cookies", "NEXT_LOCALE guarda el idioma como cookie necesaria de sesión (Path=/, SameSite=Lax). Finaliza con la sesión; la restauración de sesiones del navegador puede prolongarla. Base: § 25.2 TDDDG y art. 6.1.f RGPD. CookieYes guarda la elección en una cookie necesaria.. Base: § 25.2 TDDDG y art. 6.1.c RGPD. Estadística y marketing son opcionales y permanecen desactivados sin consentimiento expreso. Base de cookies opcionales: § 25.1 TDDDG y art. 6.1.a RGPD.."],
      ["4. Solicitudes de colaboración", "El formulario trata nombre de consulta, país, tipo de consulta, profesión, persona de contacto, correo y, opcionalmente, web y teléfono, junto con consentimiento y fecha. Finalidad: responder a la solicitud y preparar una posible colaboración, art. 6.1.b RGPD. Nuestra API envía los datos por Resend si hay una clave configurada y, en caso contrario, por FormSubmit. El destinatario predeterminado es info@cell-education.com.. El código no contiene una base de datos de formularios.."],
      ["5. Solicitudes regionales de pacientes", "Tratamos nombre, correo, código postal/ciudad, consentimiento y fecha para responder y contactar conforme a su solicitud. Base: art. 6.1.a RGPD. Puede retirar el consentimiento para el futuro en info@cell-education.com. El envío y los destinatarios se describen en el apartado 4. No envíe datos de salud; no hay campo de síntomas ni molestias.."],
      ["6. Protección de formularios", "Para prevenir abusos se usa temporalmente la IP al firmar tokens y generar una clave HMAC para limitar solicitudes en el proceso. Los contadores tienen una ventana de una hora y se eliminan en el siguiente acceso tras vencer o al terminar el proceso; los tokens duran hasta 24 horas. Hay un campo oculto y un tiempo mínimo de cumplimentación. Base: art. 6.1.f RGPD, prevención de abuso. Los registros de errores de aplicación no incluyen contenidos de formularios; véase el apartado 2 para registros del alojamiento."],
      ["7. Ubicación y búsqueda", "La función de ubicación requiere permiso del navegador. Las coordenadas se usan localmente para calcular distancias y nuestra aplicación no las envía a un servidor de geocodificación. Base: art. 6.1.a RGPD. Puede retirar el permiso en el navegador. Al buscar por localidad/código postal, nuestra API envía texto, país e idioma a Nominatim (nominatim.openstreetmap.org), sin reenviar la IP del visitante. La respuesta puede almacenarse en caché 24 horas. Base: art. 6.1.f RGPD, ofrecer la búsqueda solicitada.. Los datos y coordenadas de consultas se sirven localmente; la vista actual no carga mapas externos."],
      ["8. Vídeos, enlaces y recursos locales", "La vista previa de Vimeo se carga localmente. Solo al pulsar el botón indicado se conecta con Vimeo y pueden transmitirse IP, información del navegador y datos de uso. Base: art. 6.1.a RGPD y, cuando proceda, § 25.1 TDDDG. El reproductor usa dnt=1; esto no sustituye el consentimiento.. Al salir o recargar la página se detiene el reproductor. YouTube solo es un enlace externo. Fuentes, imágenes y scripts se sirven localmente; Google Fonts se descarga al compilar, no desde el navegador del visitante."],
      ["9. CookieYes y retirada", "Si se configura un identificador de sitio, CookieYes Limited, Reino Unido, gestiona y registra las decisiones sobre cookies. Trata decisión, fecha e identificador seudónimo de consentimiento; el proveedor indica que enmascara la IP. No se garantiza anonimato completo. Existe una decisión de adecuación de la UE para el Reino Unido. Base: art. 6.1.c en relación con art. 7.1 RGPD. Puede modificar o retirar su consentimiento desde Configuración de cookies en el pie.. Sin ID no se carga el banner. Google Analytics y Meta Pixel solo están preparados y permanecen inactivos sin IDs; la política debe completarse antes de activarlos."],
      ["10. Derechos", "Conforme a los requisitos legales, tiene derechos de acceso (art. 15 RGPD), rectificación (16), supresión (17), limitación (18), notificación (19) y portabilidad (20). Puede oponerse al tratamiento por interés legítimo por motivos de su situación particular (art. 21), y a la publicidad directa en cualquier momento. La retirada de consentimiento surte efectos futuros sin afectar a la licitud previa. Contacto: info@cell-education.com. Puede reclamar ante una autoridad de control, en particular el Comisionado de Protección de Datos y Libertad de Información de Hesse, Postfach 3163, 65021 Wiesbaden, Alemania."]
    ]
  }
};
